export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCT_FILTRATION = 'PRODUCT_FILTRATION';

export default {
	ADD_PRODUCT,
	DELETE_PRODUCT,
	PRODUCT_FILTRATION,
};
